
CREATE TABLE nm_sa_ping_diff_chk_08 (
    sa_diff_id character(8) NOT NULL,
    "time" character(14) NOT NULL,
    time_yy character varying(4) NOT NULL,
    time_mm character varying(2) NOT NULL,
    time_dd character varying(2) NOT NULL,
    time_hh character varying(2) NOT NULL,
    host_name character varying(256),
    abs_diff_avg double precision,
    pos_diff_avg double precision,
    pos_diff_count bigint,
    neg_diff_avg double precision,
    neg_diff_count bigint,
    a_rtt_min double precision,
    a_rtt_avg double precision,
    a_rtt_max double precision,
    b_rtt_min double precision,
    b_rtt_avg double precision,
    b_rtt_max double precision,
    a_jitter double precision,
    b_jitter double precision,
    a_loss double precision,
    b_loss double precision,
    reg_timestamp timestamp without time zone DEFAULT timezone('UTC'::text, now())
);
